### ISSUE TITLE
Compute Canada

### ISSUE THREAD

**Issue by twhitehead** [freuk/awesome-nix-hpc#1]
We also have regular nix with an Compute Canada (or compute cluster if you prefer) package overlay set.  Should probably move this to the CC github system for more public exposure

https://docs.computecanada.ca/wiki/Using_Nix
https://git.computecanada.ca/nix/ccpkgs
https://git.computecanada.ca/nix/training
https://hydra.sharcnet.ca/

Cheers!  -Tyson

**Comment by freuk** [comment]
I added these links to the page. Thank you, Tyson!
